In [1]:
import numpy as np

# 4.1
A =np.array([[-2,-3],[1,0]])
B =np.array([[1,1],[1,0]])
x = np.array([-1,1])
print("A:", A)
print("B:", B)
print("x:", x)

A: [[-2 -3]
 [ 1  0]]
B: [[1 1]
 [1 0]]
x: [-1  1]


In [2]:
#4.2
C = np.linalg.inv(A)
print(C)

[[-2.77555756e-17  1.00000000e+00]
 [-3.33333333e-01 -6.66666667e-01]]


In [3]:
#4.3 
print(C.dot(A))
print(A.dot(C))

[[1.00000000e+00 8.32667268e-17]
 [0.00000000e+00 1.00000000e+00]]
[[ 1.00000000e+00 -1.11022302e-16]
 [-2.77555756e-17  1.00000000e+00]]


In [4]:
#round them to int to check
print(np.around(C.dot(A)).astype(int))
print(np.around(A.dot(C)).astype(int))

[[1 0]
 [0 1]]
[[1 0]
 [0 1]]


In [5]:
#4.4 
print(np.dot(A,x))

[-1 -1]


In [6]:
#4.5
A_T = A.T
print(np.dot(A_T,A))

[[5 6]
 [6 9]]


In [8]:
#4.6
np.subtract(A.dot(x),B.dot(x))

array([-1,  0])

In [11]:
#4.7
np.linalg.norm(x)

1.4142135623730951

In [12]:
#4.8
np.linalg.norm(np.subtract(A.dot(x),B.dot(x)))

1.0

In [13]:
#4.9
print(A[:,0])

[-2  1]


In [16]:
#4.10
B[:,0] = x
print(B)

[[-1  1]
 [ 1  0]]


In [17]:
#4.11
np.multiply(A[:,0],A[:,1])

array([6, 0])